// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: finance_service.proto

package finance_service

import (
	context "context"
	global "github.com/tonychill/ifitu/apis/pb/go/global"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinanceServiceClient is the client API for FinanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinanceServiceClient interface {
	InitiateExperienceConfirmations(ctx context.Context, in *global.ExperienceConfirmationsRequest, opts ...grpc.CallOption) (*global.ExperienceConfirmationsResponse, error)
	UpdateExperienceConfirmations(ctx context.Context, in *global.ExperienceConfirmationsRequest, opts ...grpc.CallOption) (*global.ExperienceConfirmationsResponse, error)
	DeleteExperienceConfirmations(ctx context.Context, in *global.ExperienceConfirmationsRequest, opts ...grpc.CallOption) (*global.ExperienceConfirmationsResponse, error)
	CreateRates(ctx context.Context, in *CreateRatesRequest, opts ...grpc.CallOption) (*CreateRatesResponse, error)
	GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	GetPayments(ctx context.Context, in *GetPaymentsRequest, opts ...grpc.CallOption) (*GetPaymentsResponse, error)
	AddPaymentMethod(ctx context.Context, in *AddPaymentMethodRequest, opts ...grpc.CallOption) (*AddPaymentMethodResponse, error)
	GetPaymentMethods(ctx context.Context, in *GetPaymentMethodsRequest, opts ...grpc.CallOption) (*GetPaymentMethodsResponse, error)
	RemovePaymentMethod(ctx context.Context, in *RemovePaymentMethodRequest, opts ...grpc.CallOption) (*RemovePaymentMethodResponse, error)
	SaveAuthorization(ctx context.Context, in *SaveAuthorizationRequest, opts ...grpc.CallOption) (*SaveAuthorizationResponse, error)
	CaptureFunds(ctx context.Context, in *CaptureFundsRequest, opts ...grpc.CallOption) (*CaptureFundsResponse, error)
	GetPayroll(ctx context.Context, in *GetPayrollRequest, opts ...grpc.CallOption) (*GetPayrollResponse, error)
}

type financeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceServiceClient(cc grpc.ClientConnInterface) FinanceServiceClient {
	return &financeServiceClient{cc}
}

func (c *financeServiceClient) InitiateExperienceConfirmations(ctx context.Context, in *global.ExperienceConfirmationsRequest, opts ...grpc.CallOption) (*global.ExperienceConfirmationsResponse, error) {
	out := new(global.ExperienceConfirmationsResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/InitiateExperienceConfirmations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) UpdateExperienceConfirmations(ctx context.Context, in *global.ExperienceConfirmationsRequest, opts ...grpc.CallOption) (*global.ExperienceConfirmationsResponse, error) {
	out := new(global.ExperienceConfirmationsResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/UpdateExperienceConfirmations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) DeleteExperienceConfirmations(ctx context.Context, in *global.ExperienceConfirmationsRequest, opts ...grpc.CallOption) (*global.ExperienceConfirmationsResponse, error) {
	out := new(global.ExperienceConfirmationsResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/DeleteExperienceConfirmations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) CreateRates(ctx context.Context, in *CreateRatesRequest, opts ...grpc.CallOption) (*CreateRatesResponse, error) {
	out := new(CreateRatesResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/CreateRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error) {
	out := new(GetRatesResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/GetRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetPayments(ctx context.Context, in *GetPaymentsRequest, opts ...grpc.CallOption) (*GetPaymentsResponse, error) {
	out := new(GetPaymentsResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/GetPayments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) AddPaymentMethod(ctx context.Context, in *AddPaymentMethodRequest, opts ...grpc.CallOption) (*AddPaymentMethodResponse, error) {
	out := new(AddPaymentMethodResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/AddPaymentMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetPaymentMethods(ctx context.Context, in *GetPaymentMethodsRequest, opts ...grpc.CallOption) (*GetPaymentMethodsResponse, error) {
	out := new(GetPaymentMethodsResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/GetPaymentMethods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) RemovePaymentMethod(ctx context.Context, in *RemovePaymentMethodRequest, opts ...grpc.CallOption) (*RemovePaymentMethodResponse, error) {
	out := new(RemovePaymentMethodResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/RemovePaymentMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) SaveAuthorization(ctx context.Context, in *SaveAuthorizationRequest, opts ...grpc.CallOption) (*SaveAuthorizationResponse, error) {
	out := new(SaveAuthorizationResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/SaveAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) CaptureFunds(ctx context.Context, in *CaptureFundsRequest, opts ...grpc.CallOption) (*CaptureFundsResponse, error) {
	out := new(CaptureFundsResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/CaptureFunds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetPayroll(ctx context.Context, in *GetPayrollRequest, opts ...grpc.CallOption) (*GetPayrollResponse, error) {
	out := new(GetPayrollResponse)
	err := c.cc.Invoke(ctx, "/finance_service.FinanceService/GetPayroll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceServiceServer is the server API for FinanceService service.
// All implementations must embed UnimplementedFinanceServiceServer
// for forward compatibility
type FinanceServiceServer interface {
	InitiateExperienceConfirmations(context.Context, *global.ExperienceConfirmationsRequest) (*global.ExperienceConfirmationsResponse, error)
	UpdateExperienceConfirmations(context.Context, *global.ExperienceConfirmationsRequest) (*global.ExperienceConfirmationsResponse, error)
	DeleteExperienceConfirmations(context.Context, *global.ExperienceConfirmationsRequest) (*global.ExperienceConfirmationsResponse, error)
	CreateRates(context.Context, *CreateRatesRequest) (*CreateRatesResponse, error)
	GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	GetPayments(context.Context, *GetPaymentsRequest) (*GetPaymentsResponse, error)
	AddPaymentMethod(context.Context, *AddPaymentMethodRequest) (*AddPaymentMethodResponse, error)
	GetPaymentMethods(context.Context, *GetPaymentMethodsRequest) (*GetPaymentMethodsResponse, error)
	RemovePaymentMethod(context.Context, *RemovePaymentMethodRequest) (*RemovePaymentMethodResponse, error)
	SaveAuthorization(context.Context, *SaveAuthorizationRequest) (*SaveAuthorizationResponse, error)
	CaptureFunds(context.Context, *CaptureFundsRequest) (*CaptureFundsResponse, error)
	GetPayroll(context.Context, *GetPayrollRequest) (*GetPayrollResponse, error)
	mustEmbedUnimplementedFinanceServiceServer()
}

// UnimplementedFinanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFinanceServiceServer struct {
}

func (UnimplementedFinanceServiceServer) InitiateExperienceConfirmations(context.Context, *global.ExperienceConfirmationsRequest) (*global.ExperienceConfirmationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateExperienceConfirmations not implemented")
}
func (UnimplementedFinanceServiceServer) UpdateExperienceConfirmations(context.Context, *global.ExperienceConfirmationsRequest) (*global.ExperienceConfirmationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExperienceConfirmations not implemented")
}
func (UnimplementedFinanceServiceServer) DeleteExperienceConfirmations(context.Context, *global.ExperienceConfirmationsRequest) (*global.ExperienceConfirmationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExperienceConfirmations not implemented")
}
func (UnimplementedFinanceServiceServer) CreateRates(context.Context, *CreateRatesRequest) (*CreateRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRates not implemented")
}
func (UnimplementedFinanceServiceServer) GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedFinanceServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedFinanceServiceServer) GetPayments(context.Context, *GetPaymentsRequest) (*GetPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayments not implemented")
}
func (UnimplementedFinanceServiceServer) AddPaymentMethod(context.Context, *AddPaymentMethodRequest) (*AddPaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPaymentMethod not implemented")
}
func (UnimplementedFinanceServiceServer) GetPaymentMethods(context.Context, *GetPaymentMethodsRequest) (*GetPaymentMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethods not implemented")
}
func (UnimplementedFinanceServiceServer) RemovePaymentMethod(context.Context, *RemovePaymentMethodRequest) (*RemovePaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePaymentMethod not implemented")
}
func (UnimplementedFinanceServiceServer) SaveAuthorization(context.Context, *SaveAuthorizationRequest) (*SaveAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAuthorization not implemented")
}
func (UnimplementedFinanceServiceServer) CaptureFunds(context.Context, *CaptureFundsRequest) (*CaptureFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureFunds not implemented")
}
func (UnimplementedFinanceServiceServer) GetPayroll(context.Context, *GetPayrollRequest) (*GetPayrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayroll not implemented")
}
func (UnimplementedFinanceServiceServer) mustEmbedUnimplementedFinanceServiceServer() {}

// UnsafeFinanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceServiceServer will
// result in compilation errors.
type UnsafeFinanceServiceServer interface {
	mustEmbedUnimplementedFinanceServiceServer()
}

func RegisterFinanceServiceServer(s grpc.ServiceRegistrar, srv FinanceServiceServer) {
	s.RegisterService(&FinanceService_ServiceDesc, srv)
}

func _FinanceService_InitiateExperienceConfirmations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(global.ExperienceConfirmationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).InitiateExperienceConfirmations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/InitiateExperienceConfirmations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).InitiateExperienceConfirmations(ctx, req.(*global.ExperienceConfirmationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_UpdateExperienceConfirmations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(global.ExperienceConfirmationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).UpdateExperienceConfirmations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/UpdateExperienceConfirmations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).UpdateExperienceConfirmations(ctx, req.(*global.ExperienceConfirmationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_DeleteExperienceConfirmations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(global.ExperienceConfirmationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).DeleteExperienceConfirmations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/DeleteExperienceConfirmations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).DeleteExperienceConfirmations(ctx, req.(*global.ExperienceConfirmationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_CreateRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).CreateRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/CreateRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).CreateRates(ctx, req.(*CreateRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/GetRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetRates(ctx, req.(*GetRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/GetPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetPayments(ctx, req.(*GetPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_AddPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).AddPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/AddPaymentMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).AddPaymentMethod(ctx, req.(*AddPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetPaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetPaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/GetPaymentMethods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetPaymentMethods(ctx, req.(*GetPaymentMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_RemovePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).RemovePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/RemovePaymentMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).RemovePaymentMethod(ctx, req.(*RemovePaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_SaveAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).SaveAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/SaveAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).SaveAuthorization(ctx, req.(*SaveAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_CaptureFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).CaptureFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/CaptureFunds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).CaptureFunds(ctx, req.(*CaptureFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetPayroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetPayroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance_service.FinanceService/GetPayroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetPayroll(ctx, req.(*GetPayrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinanceService_ServiceDesc is the grpc.ServiceDesc for FinanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finance_service.FinanceService",
	HandlerType: (*FinanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateExperienceConfirmations",
			Handler:    _FinanceService_InitiateExperienceConfirmations_Handler,
		},
		{
			MethodName: "UpdateExperienceConfirmations",
			Handler:    _FinanceService_UpdateExperienceConfirmations_Handler,
		},
		{
			MethodName: "DeleteExperienceConfirmations",
			Handler:    _FinanceService_DeleteExperienceConfirmations_Handler,
		},
		{
			MethodName: "CreateRates",
			Handler:    _FinanceService_CreateRates_Handler,
		},
		{
			MethodName: "GetRates",
			Handler:    _FinanceService_GetRates_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _FinanceService_GetTransaction_Handler,
		},
		{
			MethodName: "GetPayments",
			Handler:    _FinanceService_GetPayments_Handler,
		},
		{
			MethodName: "AddPaymentMethod",
			Handler:    _FinanceService_AddPaymentMethod_Handler,
		},
		{
			MethodName: "GetPaymentMethods",
			Handler:    _FinanceService_GetPaymentMethods_Handler,
		},
		{
			MethodName: "RemovePaymentMethod",
			Handler:    _FinanceService_RemovePaymentMethod_Handler,
		},
		{
			MethodName: "SaveAuthorization",
			Handler:    _FinanceService_SaveAuthorization_Handler,
		},
		{
			MethodName: "CaptureFunds",
			Handler:    _FinanceService_CaptureFunds_Handler,
		},
		{
			MethodName: "GetPayroll",
			Handler:    _FinanceService_GetPayroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finance_service.proto",
}
