// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package coordinator_service;

public final class Coordinator {
  private Coordinator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetCurationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coordinator_service.GetCurationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.global.Query query = 2;</code>
     * @return Whether the query field is set.
     */
    boolean hasQuery();
    /**
     * <code>.global.Query query = 2;</code>
     * @return The query.
     */
    global.Global.Query getQuery();
    /**
     * <code>.global.Query query = 2;</code>
     */
    global.Global.QueryOrBuilder getQueryOrBuilder();

    /**
     * <pre>
     * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
     * for the week. 
     * </pre>
     *
     * <code>string page_token = 3;</code>
     * @return The pageToken.
     */
    java.lang.String getPageToken();
    /**
     * <pre>
     * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
     * for the week. 
     * </pre>
     *
     * <code>string page_token = 3;</code>
     * @return The bytes for pageToken.
     */
    com.google.protobuf.ByteString
        getPageTokenBytes();

    /**
     * <code>int32 page = 4;</code>
     * @return The page.
     */
    int getPage();

    /**
     * <pre>
     ** Example query: 
     *  "rate_range": "[500-1000]",
     *  "rate_interval": "hourly|daily|weekly|monthly",
     *  "rate_currency": "USD|EUR|GBP|BTC|ETH",
     *  "location_names": "st. john, st. thomas, jamaica, ...",
     *  "location_geos": "[18.12345,64.35465],[18.12345,64.35465],...",
     *  "location_raduis": "50mi,25mi...",
     * </pre>
     *
     * <code>int32 page_size = 5;</code>
     * @return The pageSize.
     */
    int getPageSize();
  }
  /**
   * Protobuf type {@code coordinator_service.GetCurationRequest}
   */
  public static final class GetCurationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:coordinator_service.GetCurationRequest)
      GetCurationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetCurationRequest.newBuilder() to construct.
    private GetCurationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCurationRequest() {
      pageToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetCurationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coordinator_service.Coordinator.internal_static_coordinator_service_GetCurationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coordinator_service.Coordinator.internal_static_coordinator_service_GetCurationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coordinator_service.Coordinator.GetCurationRequest.class, coordinator_service.Coordinator.GetCurationRequest.Builder.class);
    }

    public static final int QUERY_FIELD_NUMBER = 2;
    private global.Global.Query query_;
    /**
     * <code>.global.Query query = 2;</code>
     * @return Whether the query field is set.
     */
    @java.lang.Override
    public boolean hasQuery() {
      return query_ != null;
    }
    /**
     * <code>.global.Query query = 2;</code>
     * @return The query.
     */
    @java.lang.Override
    public global.Global.Query getQuery() {
      return query_ == null ? global.Global.Query.getDefaultInstance() : query_;
    }
    /**
     * <code>.global.Query query = 2;</code>
     */
    @java.lang.Override
    public global.Global.QueryOrBuilder getQueryOrBuilder() {
      return getQuery();
    }

    public static final int PAGE_TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object pageToken_;
    /**
     * <pre>
     * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
     * for the week. 
     * </pre>
     *
     * <code>string page_token = 3;</code>
     * @return The pageToken.
     */
    @java.lang.Override
    public java.lang.String getPageToken() {
      java.lang.Object ref = pageToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pageToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
     * for the week. 
     * </pre>
     *
     * <code>string page_token = 3;</code>
     * @return The bytes for pageToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPageTokenBytes() {
      java.lang.Object ref = pageToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_FIELD_NUMBER = 4;
    private int page_;
    /**
     * <code>int32 page = 4;</code>
     * @return The page.
     */
    @java.lang.Override
    public int getPage() {
      return page_;
    }

    public static final int PAGE_SIZE_FIELD_NUMBER = 5;
    private int pageSize_;
    /**
     * <pre>
     ** Example query: 
     *  "rate_range": "[500-1000]",
     *  "rate_interval": "hourly|daily|weekly|monthly",
     *  "rate_currency": "USD|EUR|GBP|BTC|ETH",
     *  "location_names": "st. john, st. thomas, jamaica, ...",
     *  "location_geos": "[18.12345,64.35465],[18.12345,64.35465],...",
     *  "location_raduis": "50mi,25mi...",
     * </pre>
     *
     * <code>int32 page_size = 5;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (query_ != null) {
        output.writeMessage(2, getQuery());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pageToken_);
      }
      if (page_ != 0) {
        output.writeInt32(4, page_);
      }
      if (pageSize_ != 0) {
        output.writeInt32(5, pageSize_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (query_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getQuery());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pageToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pageToken_);
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, page_);
      }
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pageSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coordinator_service.Coordinator.GetCurationRequest)) {
        return super.equals(obj);
      }
      coordinator_service.Coordinator.GetCurationRequest other = (coordinator_service.Coordinator.GetCurationRequest) obj;

      if (hasQuery() != other.hasQuery()) return false;
      if (hasQuery()) {
        if (!getQuery()
            .equals(other.getQuery())) return false;
      }
      if (!getPageToken()
          .equals(other.getPageToken())) return false;
      if (getPage()
          != other.getPage()) return false;
      if (getPageSize()
          != other.getPageSize()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasQuery()) {
        hash = (37 * hash) + QUERY_FIELD_NUMBER;
        hash = (53 * hash) + getQuery().hashCode();
      }
      hash = (37 * hash) + PAGE_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getPageToken().hashCode();
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coordinator_service.Coordinator.GetCurationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coordinator_service.Coordinator.GetCurationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coordinator_service.GetCurationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coordinator_service.GetCurationRequest)
        coordinator_service.Coordinator.GetCurationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coordinator_service.Coordinator.internal_static_coordinator_service_GetCurationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coordinator_service.Coordinator.internal_static_coordinator_service_GetCurationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coordinator_service.Coordinator.GetCurationRequest.class, coordinator_service.Coordinator.GetCurationRequest.Builder.class);
      }

      // Construct using coordinator_service.Coordinator.GetCurationRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (queryBuilder_ == null) {
          query_ = null;
        } else {
          query_ = null;
          queryBuilder_ = null;
        }
        pageToken_ = "";

        page_ = 0;

        pageSize_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coordinator_service.Coordinator.internal_static_coordinator_service_GetCurationRequest_descriptor;
      }

      @java.lang.Override
      public coordinator_service.Coordinator.GetCurationRequest getDefaultInstanceForType() {
        return coordinator_service.Coordinator.GetCurationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public coordinator_service.Coordinator.GetCurationRequest build() {
        coordinator_service.Coordinator.GetCurationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coordinator_service.Coordinator.GetCurationRequest buildPartial() {
        coordinator_service.Coordinator.GetCurationRequest result = new coordinator_service.Coordinator.GetCurationRequest(this);
        if (queryBuilder_ == null) {
          result.query_ = query_;
        } else {
          result.query_ = queryBuilder_.build();
        }
        result.pageToken_ = pageToken_;
        result.page_ = page_;
        result.pageSize_ = pageSize_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coordinator_service.Coordinator.GetCurationRequest) {
          return mergeFrom((coordinator_service.Coordinator.GetCurationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coordinator_service.Coordinator.GetCurationRequest other) {
        if (other == coordinator_service.Coordinator.GetCurationRequest.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          mergeQuery(other.getQuery());
        }
        if (!other.getPageToken().isEmpty()) {
          pageToken_ = other.pageToken_;
          onChanged();
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                input.readMessage(
                    getQueryFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 18
              case 26: {
                pageToken_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 32: {
                page_ = input.readInt32();

                break;
              } // case 32
              case 40: {
                pageSize_ = input.readInt32();

                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private global.Global.Query query_;
      private com.google.protobuf.SingleFieldBuilderV3<
          global.Global.Query, global.Global.Query.Builder, global.Global.QueryOrBuilder> queryBuilder_;
      /**
       * <code>.global.Query query = 2;</code>
       * @return Whether the query field is set.
       */
      public boolean hasQuery() {
        return queryBuilder_ != null || query_ != null;
      }
      /**
       * <code>.global.Query query = 2;</code>
       * @return The query.
       */
      public global.Global.Query getQuery() {
        if (queryBuilder_ == null) {
          return query_ == null ? global.Global.Query.getDefaultInstance() : query_;
        } else {
          return queryBuilder_.getMessage();
        }
      }
      /**
       * <code>.global.Query query = 2;</code>
       */
      public Builder setQuery(global.Global.Query value) {
        if (queryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          query_ = value;
          onChanged();
        } else {
          queryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.global.Query query = 2;</code>
       */
      public Builder setQuery(
          global.Global.Query.Builder builderForValue) {
        if (queryBuilder_ == null) {
          query_ = builderForValue.build();
          onChanged();
        } else {
          queryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.global.Query query = 2;</code>
       */
      public Builder mergeQuery(global.Global.Query value) {
        if (queryBuilder_ == null) {
          if (query_ != null) {
            query_ =
              global.Global.Query.newBuilder(query_).mergeFrom(value).buildPartial();
          } else {
            query_ = value;
          }
          onChanged();
        } else {
          queryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.global.Query query = 2;</code>
       */
      public Builder clearQuery() {
        if (queryBuilder_ == null) {
          query_ = null;
          onChanged();
        } else {
          query_ = null;
          queryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.global.Query query = 2;</code>
       */
      public global.Global.Query.Builder getQueryBuilder() {
        
        onChanged();
        return getQueryFieldBuilder().getBuilder();
      }
      /**
       * <code>.global.Query query = 2;</code>
       */
      public global.Global.QueryOrBuilder getQueryOrBuilder() {
        if (queryBuilder_ != null) {
          return queryBuilder_.getMessageOrBuilder();
        } else {
          return query_ == null ?
              global.Global.Query.getDefaultInstance() : query_;
        }
      }
      /**
       * <code>.global.Query query = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          global.Global.Query, global.Global.Query.Builder, global.Global.QueryOrBuilder> 
          getQueryFieldBuilder() {
        if (queryBuilder_ == null) {
          queryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              global.Global.Query, global.Global.Query.Builder, global.Global.QueryOrBuilder>(
                  getQuery(),
                  getParentForChildren(),
                  isClean());
          query_ = null;
        }
        return queryBuilder_;
      }

      private java.lang.Object pageToken_ = "";
      /**
       * <pre>
       * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
       * for the week. 
       * </pre>
       *
       * <code>string page_token = 3;</code>
       * @return The pageToken.
       */
      public java.lang.String getPageToken() {
        java.lang.Object ref = pageToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pageToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
       * for the week. 
       * </pre>
       *
       * <code>string page_token = 3;</code>
       * @return The bytes for pageToken.
       */
      public com.google.protobuf.ByteString
          getPageTokenBytes() {
        java.lang.Object ref = pageToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pageToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
       * for the week. 
       * </pre>
       *
       * <code>string page_token = 3;</code>
       * @param value The pageToken to set.
       * @return This builder for chaining.
       */
      public Builder setPageToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pageToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
       * for the week. 
       * </pre>
       *
       * <code>string page_token = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageToken() {
        
        pageToken_ = getDefaultInstance().getPageToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * st joun home with 4 beds for a group of 8 ranging between 200 - 500 
       * for the week. 
       * </pre>
       *
       * <code>string page_token = 3;</code>
       * @param value The bytes for pageToken to set.
       * @return This builder for chaining.
       */
      public Builder setPageTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pageToken_ = value;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>int32 page = 4;</code>
       * @return The page.
       */
      @java.lang.Override
      public int getPage() {
        return page_;
      }
      /**
       * <code>int32 page = 4;</code>
       * @param value The page to set.
       * @return This builder for chaining.
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <pre>
       ** Example query: 
       *  "rate_range": "[500-1000]",
       *  "rate_interval": "hourly|daily|weekly|monthly",
       *  "rate_currency": "USD|EUR|GBP|BTC|ETH",
       *  "location_names": "st. john, st. thomas, jamaica, ...",
       *  "location_geos": "[18.12345,64.35465],[18.12345,64.35465],...",
       *  "location_raduis": "50mi,25mi...",
       * </pre>
       *
       * <code>int32 page_size = 5;</code>
       * @return The pageSize.
       */
      @java.lang.Override
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <pre>
       ** Example query: 
       *  "rate_range": "[500-1000]",
       *  "rate_interval": "hourly|daily|weekly|monthly",
       *  "rate_currency": "USD|EUR|GBP|BTC|ETH",
       *  "location_names": "st. john, st. thomas, jamaica, ...",
       *  "location_geos": "[18.12345,64.35465],[18.12345,64.35465],...",
       *  "location_raduis": "50mi,25mi...",
       * </pre>
       *
       * <code>int32 page_size = 5;</code>
       * @param value The pageSize to set.
       * @return This builder for chaining.
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** Example query: 
       *  "rate_range": "[500-1000]",
       *  "rate_interval": "hourly|daily|weekly|monthly",
       *  "rate_currency": "USD|EUR|GBP|BTC|ETH",
       *  "location_names": "st. john, st. thomas, jamaica, ...",
       *  "location_geos": "[18.12345,64.35465],[18.12345,64.35465],...",
       *  "location_raduis": "50mi,25mi...",
       * </pre>
       *
       * <code>int32 page_size = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:coordinator_service.GetCurationRequest)
    }

    // @@protoc_insertion_point(class_scope:coordinator_service.GetCurationRequest)
    private static final coordinator_service.Coordinator.GetCurationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coordinator_service.Coordinator.GetCurationRequest();
    }

    public static coordinator_service.Coordinator.GetCurationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCurationRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetCurationRequest>() {
      @java.lang.Override
      public GetCurationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetCurationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCurationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coordinator_service.Coordinator.GetCurationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coordinator_service_GetCurationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coordinator_service_GetCurationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021coordinator.proto\022\023coordinator_service" +
      "\032\014global.proto\"g\n\022GetCurationRequest\022\034\n\005" +
      "query\030\002 \001(\0132\r.global.Query\022\022\n\npage_token" +
      "\030\003 \001(\t\022\014\n\004page\030\004 \001(\005\022\021\n\tpage_size\030\005 \001(\0052" +
      "\024\n\022CoordinatorServiceB;Z9github.com/tony" +
      "chill/ifitu/apis/pb/go/coordinator_servi" +
      "ceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          global.Global.getDescriptor(),
        });
    internal_static_coordinator_service_GetCurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coordinator_service_GetCurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coordinator_service_GetCurationRequest_descriptor,
        new java.lang.String[] { "Query", "PageToken", "Page", "PageSize", });
    global.Global.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
